server:
  port: 8761

spring:
  application:
    name: EUREKA-SERVER

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info,metrics

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false